### ISSUE TITLE
Guide on the installation of Azure Activity Log Dashboard

### ISSUE THREAD

**Issue by pir8g33k** [bhozar/grafana-dashboards#5]
Is there full guide on the installation of Azure Activity Log Dashboard @bhozar i really need this dashboard to monitor azure, and do you have dashboard for azure sentinel also? can i have your contact email address please, i need your services with azure monitoring

**Comment by bhozar** [comment]
@pir8g33k There is a link the the MS documentation for outputting the Azure Activity log to blob storage. The link is in the readme. All the files required are in the repo for the dashboard. Other than that, there is no guide.
