### ISSUE TITLE
drop {} on postfix/smtpd: NOQUEUE

### ISSUE THREAD

**Issue by mirsafari** [bhozar/grafana-dashboards#6]
Logstash drops all postfix events that do not have postfix_queueid
```
if ![postfix_queueid] and "postfix" in [tags] {
    drop {}
```
Sometimes in troubleshooting, those messages contain most info about a certan problem. Examples:
`Jun  9 20:29:01 HOSTNAME postfix/smtpd[239709]: NOQUEUE: milter-reject: RCPT from unknown[XXX.XXX.XXX.XXX]: 550 5.7.0 Your server IP address [XXX.XXX.XXX.XXX] does not have a valid reverse DNS entry. See http://spamauditor.org/best-practices/check_dynamic_reverse_dns/ for more information. Protection provided by MagicSpam 2.0.18-1 http://www.magicspam.com`

`Jun 10 00:59:01 HOSTNAME postfix/smtpd[96322]: NOQUEUE: reject: RCPT from unknown[XXX.XXX.XXX.XXX]: 554 5.7.1 Service unavailable; Client host [XXX.XXX.XXX.XXX] blocked using zen.spamhaus.org; https://www.spamhaus.org/sbl/query/SBLCSS / https://www.spamhaus.org/query/ip/XXX.XXX.XXX.XXX`

`NOQUEUE: reject: RCPT from HOSTNAME[XXX.XXX.XXX.XXX]: 554 5.7.1 <email@mail.net>: Recipient address rejected: Blacklisted on this mail filter. Contact hd@domain.tld; from=<email@mail.net> to=<email2@mail.net> proto=ESMTP helo=<HOSTNAME>`

Or if you are using something for quotas:
`NOQUEUE: reject: RCPT from HOSTNAME[XXX.XXX.XXX.XXX]: 554 5.7.1 <email@mail.net>: Recipient address rejected: Sender quota limit reached.; from=<email@mail.net> to=<email2@mail.net> proto=ESMTP helo=<HOSTNAME>`

Maybe those logs should be parsed and included in dashboards. I'm willing to contribute to the solution, but I'm interested in the line of thought on discarding those logs

**Comment by bhozar** [comment]
@mirsafari Interesting find. I hadn't noticed those in my logs, but ideally they should be captured and displayed in the dashboard. I presumed all the messages would have a queueid of some kind and a lot of the setups out there seemed to also drop the messages without queueid.

May be worth not dropping them and seeing if they are useful and should be reported, but looking at your text, they do look useful.

**Comment by mirsafari** [comment]
I've removed:
```
if ![postfix_queueid] and "postfix" in [tags] {
    drop {}
```
and just proceded with aggregation like usual:
```conf
filter {
  if [postfix_program] == "postfix/smtpd" and [postfix_client_ip] {
    aggregate {
      task_id => "%{postfix_queueid}"
      code => "
        map['postfix_client_hostname'] = event.get('postfix_client_hostname')
        map['postfix_client_ip'] = event.get('postfix_client_ip')
      "
      map_action => "create_or_update"
    }
  } else if [postfix_program] == "postfix/cleanup" and [postfix_message-id] {
    aggregate {
      task_id => "%{postfix_queueid}"
      code => "
        map['postfix_message-id'] = event.get('postfix_message-id')
      "
      map_action => "create_or_update"
    }
....
```
Since GROK filters for NOQUEUE are already in place, I get parsed logs, and these errors that are present in NOQUEUE like usual. Because most NOQUEUE messages have the postfix status code enhanced field, those are also visible in dashboards showing 4.X.X or 5.X.X errors. It's been working OK for a couple of weeks now with no problems
