### ISSUE TITLE
postfixsmtpemail_opendkim conf logstash

### ISSUE THREAD

**Issue by reox22** [bhozar/grafana-dashboards#9]
Hi,
beautifull dashboard,

have you an documentation  for the logstash conf other than these conf file.
that i have understand but not sure :

on the smtp server -> filebeat
on the grafana server : logstash, kibana, prometheus and grafana

i will not talk about prometheus part who is display well in the dashboard

-1. filebeat part
/etc/filebeat/filebeat.yml
  filebeat.inputs:
paths:
    - /var/log/maillog
output.logstash:
hosts: ["<fqdn.grafanaserver>:5044"]

-2. logstash
/etc/logstash/conf.d
02-beats-input.conf  30-filter-postfix-prepare.conf  31-filter-postfix.conf  32-filter-postfix-aggregate.conf  40-output.conf

02-beats-input.conf
input {
  beats {
    port => 5044
    ssl => false
  }
}

40-output.conf
output {
  elasticsearch {
   hosts => ["<ip grafana server>:9200"]
     index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
  }
 stdout {
     codec => rubydebug
 }
}

/etc/logstash/patterns.d
opendkim.grok  postfix.grok

chown logstash on the two folder and files 

can you tell me what step i have forgot?

for the moment i have value only in the block server status who data come from prometheus part.

**Comment by bhozar** [comment]
Have you checked ElasticSearch to see if it is getting any content from logstash? Nothing is jumping out as missing, but could be a problem with your general setup if the first thing you are running is all the Postfix grok and configurations. Check the logs. Elastic search or logstssh may be throwing errors.

**Comment by bhozar** [comment]
@reox22 Any update?

**Comment by reox22** [comment]
for the moment not find the issue,  i always investigate

**Comment by reox22** [comment]
3 weeks after ,now its working 👍 .

explanation by default .
in configuration of postfix : in master.cf
the default service is name postfix.

in our case we have several transport.the name have is importance.
**smtp-gmail** unix -       -       n       -       100      smtp
         -o syslog_name=smtp-gmail

-1. filebeat part
/etc/filebeat/filebeat.yml
filebeat.inputs:
- type : log
  paths: /var/log/maillog
  exclude_lines: ['^lost connection after EHLO from postfix-', 'disconnect from postfix-']
  fields:
    postfix: true
  fields_under_root: true
  tags : ["postfix","**smtp-gmail**"]
  close.removed: true
  close.renamed: true

output.logstash:
hosts: ["<fqdn.grafanaserver>:5044"]

for the tags not sure at this moment, i tks i generate double of data


in logstash.conf
-2. logstash
/etc/logstash/conf.d

30-filter-postfix-prepare.conf
i have ajust the filter
filter {
  if "postfix" in [tags] {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP} %{SYSLOGHOST} %{DATA:program}(?:\[%{POSINT}\])?: %{GREEDYDATA:message}" }
      overwrite => "message"
    }
  }
  if "**smtp-gmail**" in [tags] {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP} %{SYSLOGHOST} %{DATA:program}(?:\[%{POSINT}\])?: %{GREEDYDATA:message}" }
      overwrite => "message"
    }
  }
}

in
31-filter-postfix.conf
... modifyied
} else if [program] =~ /^postfix.*\/sendmail$/ {
        grok {
            patterns_dir   => "/etc/logstash/patterns.d"
            match          => [ "message", "^%{POSTFIX_SENDMAIL}$" ]
            tag_on_failure => [ "_grok_postfix_sendmail_nomatch" ]
            add_tag        => [ "_grok_postfix_success" ]
        }
    } else if [program] =~ /^**smtp-gmail**.*\/smtp$/ {
        grok {
            patterns_dir   => "/etc/logstash/patterns.d"
            match          => [ "message", "^%{POSTFIX_SMTP}$" ]
            tag_on_failure => [ "_grok_postfix_smtp_nomatch" ]
            add_tag        => [ "_grok_postfix_success" ]
        }
    } else if [program] =~ /^postfix.*\/lmtp$/ {
        grok {
            patterns_dir   => "/etc/logstash/patterns.d"
            match          => [ "message", "^%{POSTFIX_LMTP}$" ]
            tag_on_failure => [ "_grok_postfix_lmtp_nomatch" ]
            add_tag        => [ "_grok_postfix_success" ]
        }
    } else if [program] =~ /^postfix.*\/smtpd$/ {
...

in 32-filter-postfix-aggregate.conf
...
} else if [program] == "postfixl/smtp" {
    aggregate {
...
come
...
} else if [program] == "**smtp-gmail**/smtp" {
    aggregate {
...

in patterns no change.

in finally in dashboard.
replace in queries : postfix/smtp by **smtp-gmail**/smtp for us.

i have past three week for find this explanation.
if someone have custom is postfix conf, be carefull, but this dashboard is very good.

tks again a lot.
